/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;
import Acciones.Acciones;
import net.proteanit.sql.DbUtils;
import Clases.DetallePedidos;
import Clases.Cliente;
import Clases.Pedido;
import Clases.Producto;
import Conexiones.Connect;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.*;
import javax.*;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author jorci
 */
public class DashboardFrme extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrme
     */
    public DashboardFrme() {
        initComponents();
        
        Acciones.displayTable(jTable2, "SELECT * FROM CLIENTE");
        Acciones.displayTable(jTable4, "SELECT * FROM PRODUCTO");
        addValuesComoboBox();
        addValuesComboBox2();
        Acciones.limpiarTabla(jTable1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        id_clienteText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nombreClienteText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        apellidoClienteText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        direccionClienteText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        correoClienteText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dniClienteText = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        idProductoText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        colorProductoText = new javax.swing.JTextField();
        tallaProductoText = new javax.swing.JTextField();
        precioProductoText = new javax.swing.JTextField();
        nombreProductoText = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cantidadPedidoText = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<Cliente>();
        jComboBox2 = new javax.swing.JComboBox<Producto>();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1560, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, -30, 1560, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 50));

        jPanel2.setBackground(new java.awt.Color(254, 114, 93));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clientes");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 48));

        jPanel3.setBackground(new java.awt.Color(254, 114, 93));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Productos");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 48));

        jPanel4.setBackground(new java.awt.Color(254, 114, 93));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pedidos");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 48));

        jPanel5.setBackground(new java.awt.Color(254, 114, 93));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Volver");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 180, 48));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 256, 720));

        jPanel6.setBackground(new java.awt.Color(250, 247, 245));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Id_Cliente");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 20));
        jPanel9.add(id_clienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        jLabel11.setText("Nombre");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));
        jPanel9.add(nombreClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, -1));

        jLabel12.setText("Apellido");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel9.add(apellidoClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, -1));

        jLabel13.setText("Dirección");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        jPanel9.add(direccionClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, -1));

        jLabel14.setText("Correo ");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        jPanel9.add(correoClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, -1));

        jLabel15.setText("DNI");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        dniClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniClienteTextActionPerformed(evt);
            }
        });
        jPanel9.add(dniClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 190, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/agregar.png"))); // NOI18N
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 50, 50));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/eliminar.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 50, 50));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/Editar.png"))); // NOI18N
        jPanel18.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel9.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 50, 50));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 250, 600));

        jScrollPane2.setBackground(new java.awt.Color(254, 114, 93));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "nombre", "apellido", "dirección", "correo", "dni"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 640, 490));

        jTabbedPane1.addTab("tab1", jPanel6);

        jPanel7.setBackground(new java.awt.Color(250, 247, 245));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("id_producto");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel12.add(idProductoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, -1));

        jLabel17.setText("Color");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel18.setText("Talla");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel19.setText("Precio");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel20.setText("Nombre");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel12.add(colorProductoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, -1));
        jPanel12.add(tallaProductoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, -1));
        jPanel12.add(precioProductoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, -1));
        jPanel12.add(nombreProductoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/agregar.png"))); // NOI18N
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 50, 50));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/Editar.png"))); // NOI18N
        jPanel19.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel12.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 50, 50));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
        });
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/eliminar.png"))); // NOI18N
        jPanel20.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel12.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 50, 50));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 250, 490));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_producto", "color", "talla", "precio", "nombre"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 600, 450));

        jTabbedPane1.addTab("tab2", jPanel7);

        jPanel8.setBackground(new java.awt.Color(250, 247, 245));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("fecha");
        jPanel15.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        jLabel22.setText("cliente");
        jPanel15.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel23.setText("producto");
        jPanel15.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel24.setText("cantidad");
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel15.add(cantidadPedidoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, -1));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/agregar.png"))); // NOI18N
        jPanel16.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 50, 50));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/listo.png"))); // NOI18N
        jPanel17.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 50, 50));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel15.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel15.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, -1));

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jPanel15.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, -1));

        jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 250, 420));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_producto", "nombre", "talla", "cantidad", "valor"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 610, 290));

        jTabbedPane1.addTab("tab3", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -20, 1023, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        MainFrame mainframe = new MainFrame();
        mainframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void dniClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniClienteTextActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        try {
            // TODO add your handling code here:

            Cliente client = new Cliente(Integer.parseInt(id_clienteText.getText()), nombreClienteText.getText(), apellidoClienteText.getText(), direccionClienteText.getText(), correoClienteText.getText(), Integer.parseInt(dniClienteText.getText()));
            client.registrarCliente();
            Acciones.displayTable(jTable2, "SELECT * FROM CLIENTE");
            addValuesComoboBox();
            Acciones.generarSuccesFrame("Cliente registrado con éxito");
        } catch (Exception ex) {
            Acciones.generarErrorFrame("No se pudo registrar el cliente");
        }
        
        


    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        Acciones.delete(jTable2, "DELETE FROM CLIENTE WHERE ID_CLIENTE = '", "SELECT * FROM CLIENTE");
        
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
        modificarCLiente();
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            Producto product = new Producto(Integer.parseInt(idProductoText.getText()), colorProductoText.getText(), tallaProductoText.getText(), Integer.parseInt(precioProductoText.getText()), nombreProductoText.getText());
            product.registrarProducto();
            Acciones.displayTable(jTable4, "SELECT * FROM PRODUCTO");
            addValuesComboBox2();
            Acciones.generarSuccesFrame("Producto registrado con éxito");

        } catch (Exception ex) {
            Acciones.generarErrorFrame("No se pudo registrar el producto");

        }
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
        // TODO add your handling code here:
        Acciones.delete(jTable4, "DELETE FROM PRODUCTO WHERE ID_PRODUCTO = '", "SELECT * FROM PRODUCTO");
        
        
    }//GEN-LAST:event_jPanel20MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        // TODO add your handling code here:
        modificarProducto();
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        // TODO add your handling code here:
        agregarFilas();


    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked

        // Creacion del pedido y del detalle pedido
       
        try {
            Random rand = new Random();
                int a = rand.nextInt(1000);
                

                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                if (tblModel.getRowCount() == 0) {
                    Acciones.generarErrorFrame("La tabla está vacía");
                    
                    
                }else{
                    
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date date = sdf.parse(((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText()); 
                java.sql.Date sqlDate = new Date(date.getTime());         
                System.out.println("String converted to java.sql.Date :" + sqlDate);
                    Pedido order = new Pedido(a, sqlDate, "EN PROCESO", jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).getCodigo());
                order.registrarPedido();
                    for (int i = 0; i < tblModel.getRowCount(); i++) {
                    DetallePedidos detail = new DetallePedidos(a, Integer.parseInt(tblModel.getValueAt(i, 3).toString()), Integer.parseInt(tblModel.getValueAt(i, 0).toString()));
                    detail.registrarDetallePedidos();
                    Acciones.generarSuccesFrame("Pedido registrado con éxito");
                }
                }

                

            

           
        } catch (Exception ex) {
            Acciones.generarErrorFrame("No se pudo registrar el pedido");
        }
        

    }//GEN-LAST:event_jPanel17MouseClicked



    
//funciones de combobox
    private void addValuesComoboBox() {
        try {
            jComboBox1.removeAllItems();
            Connection conn = Connect.getConnection();
            String sql = "SELECT * FROM CLIENTE";
            PreparedStatement pst = conn.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {

                jComboBox1.addItem(
                        new Cliente(Integer.parseInt(rs.getString("ID_CLIENTE")), rs.getString("NOMBRES"), rs.getString("APELIIDOS"), rs.getString("DIRECCION_VIVVIENDA"), rs.getString("EMAIL"), Integer.parseInt(rs.getString("DNI"))));
            }//end while
            pst.executeUpdate();
            pst.close();
            conn.close();
        } catch (Exception e) {
               
        }
    }

    private void addValuesComboBox2() {
        try {
            jComboBox2.removeAllItems();
            Connection conn = Connect.getConnection();
            String sql = "SELECT * FROM PRODUCTO";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {

                jComboBox2.addItem(
                        new Producto(Integer.parseInt(rs.getString("ID_PRODUCTO")), rs.getString("COLOR"), rs.getString("TALLA"), Integer.parseInt(rs.getString("PRECIO")), rs.getString("NOMBRE")));
            }//end while

            pst.executeUpdate();
            pst.close();
            conn.close();
        } catch (Exception e) {
           

        }

    }

   

//Area cliente


    public void modificarCLiente() {
        int fila = jTable2.getSelectedRow();

        int id = Integer.parseInt(this.jTable2.getValueAt(fila, 0).toString());
        String nom = jTable2.getValueAt(fila, 1).toString();
        String ape = jTable2.getValueAt(fila, 2).toString();
        String dir = jTable2.getValueAt(fila, 3).toString();
        String ema = jTable2.getValueAt(fila, 4).toString();
        String dni = jTable2.getValueAt(fila, 5).toString();

        try {
            Connection conn = Connect.getConnection();
            String sql = "UPDATE CLIENTE SET NOMBRES='" + nom + "',APELIIDOS = '" + ape + "',DIRECCION_VIVVIENDA = '" + dir + "',EMAIL ='" + ema + "',DNI ='" + dni + "' WHERE ID_CLIENTE ='" + id + "'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            Acciones.displayTable(jTable2, "SELECT * FROM CLIENTE");
            pst.executeUpdate();
            pst.close();
            conn.close();
            Acciones.generarSuccesFrame("Cliente modificado con éxito");
        } catch (Exception e) {
            Acciones.generarErrorFrame("Selecciona una tabla");
        }

    }

//Area Producto
  

    public void modificarProducto() {
        int fila = jTable4.getSelectedRow();

        int id = Integer.parseInt(this.jTable4.getValueAt(fila, 0).toString());
        String col = jTable4.getValueAt(fila, 1).toString();
        String tal = jTable4.getValueAt(fila, 2).toString();
        String pre = jTable4.getValueAt(fila, 3).toString();
        String nom = jTable4.getValueAt(fila, 4).toString();

        try {
            Connection conn = Connect.getConnection();
            String sql = "UPDATE PRODUCTO SET COLOR='" + col + "',TALLA = '" + tal + "',PRECIO = '" + pre + "',NOMBRE ='" + nom + "' WHERE ID_PRODUCTO ='" + id + "'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            Acciones.displayTable(jTable4, "SELECT * FROM PRODUCTO");
            pst.executeUpdate();
            pst.close();
            conn.close();
            Acciones.generarSuccesFrame("Producto modificado con éxito");
        } catch (Exception e) {
            Acciones.generarErrorFrame("Selecciona una tabla");
        }

    }

    //area pedidos
    private void agregarFilas() {

        try {
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             int id= jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getCodigo();
             int a = Integer.parseInt(cantidadPedidoText.getText());
             
            
                 
                 
                model.addRow(new Object[]{jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getCodigo(), jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getNombre(), jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getTalla(),
                    a, a * jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getPrecio()});
           
                 
             
                

        } catch (Exception e) {
            Acciones.generarErrorFrame("Ingresa un valor correcto");
        }

    }
    
    
    private void combinarPorId(){
        
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        int id= jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).getCodigo();
        if (tblModel.getRowCount() == 0) {
                    
                    return;
                    
                }else{
            for (int i = 0; i < tblModel.getRowCount(); i++) {
                if (id == Integer.parseInt(jTable1.getValueAt(i, 0).toString())) {
                    tblModel.setValueAt( Integer.parseInt(tblModel.getValueAt(i, 3).toString())+Integer.parseInt(cantidadPedidoText.getText()), 1, 1);
                         
                }
                    
                    
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoClienteText;
    private javax.swing.JTextField cantidadPedidoText;
    private javax.swing.JTextField colorProductoText;
    private javax.swing.JTextField correoClienteText;
    private javax.swing.JTextField direccionClienteText;
    private javax.swing.JTextField dniClienteText;
    private javax.swing.JTextField idProductoText;
    private javax.swing.JTextField id_clienteText;
    private javax.swing.JComboBox<Cliente> jComboBox1;
    private javax.swing.JComboBox<Producto> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField nombreClienteText;
    private javax.swing.JTextField nombreProductoText;
    private javax.swing.JTextField precioProductoText;
    private javax.swing.JTextField tallaProductoText;
    // End of variables declaration//GEN-END:variables
}
